### ISSUE TITLE
Unable to change aux parameters via rqt

### ISSUE THREAD

**Issue by poornimajd** [carnegierobotics/multisense_ros#110]
I have installed the ros noetic multisense driver in a docker container . But when I launch the node:
`roslaunch multisense_bringup multisense.launch ip_address:="10.66.171.21" mtu:="1500"`

I get this warning:
Reconfigure: MultiSense firmware version does not support the updated aux camera exposure controls. The ROS driver will work normally, but you will have limited control over aux camera exposure parameters. Please use the 2eae444 has of multisene_ros or contact support@carnegierobotics.com for a updated firmware version greater than 6.0 to enable aux camera exposure controls.

Hence I am unable to change the settings such as aux_gamma etc using rqt
I tried to git checkout the commit  2eae444 , but I end up getting errors while building the ros package.
Is there any workaround to this issue?

**Comment by mattalvarado** [comment]
Hi @poornimajd you can download the latest version of MultiSense firmware here: https://carnegierobotics.com/support

**Comment by poornimajd** [comment]
Thank you for the reply, but when I tried using the link to update firmware
https://docs.carnegierobotics.com/docs/firmware/update.html#update-firmware

I get the error as below


curl -T /home/user/update/update_enc_20231005-2214_C22F29D0.img tftp://10.66.171.21/update_enc_20231005-2214_C22F29D0.img
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 98.6M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 98.6M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (68) TFTP: File Not Found
The path for the image is correct.
I also tried using tftp in octet mode.

**Comment by mattalvarado** [comment]
Hi @poornimajd your command should be updated to:

`curl -T /home/user/update/update_enc_20231005-2214_C22F29D0.img tftp://10.66.171.21/update.img`
