### ISSUE TITLE
multisense_ros failing to build on Ubuntu Focal in ROS Noetic

### ISSUE THREAD

**Issue by sloretz** [carnegierobotics/multisense_ros#3]
It looks like `multisense_ros` is failing to build on Ubuntu Focal, which is [a required support platform for ROS Noetic](https://www.ros.org/reps/rep-0003.html#noetic-ninjemys-may-2020-may-2025).

* http://build.ros.org/job/Nbin_uF64__multisense_ros__ubuntu_focal_amd64__binary/
* http://build.ros.org/job/Nbin_ufhf_uFhf__multisense_ros__ubuntu_focal_armhf__binary/
* http://build.ros.org/job/Nbin_ufv8_uFv8__multisense_ros__ubuntu_focal_arm64__binary/

There appear to be many compiler errors about missing Cv types

```
16:47:56 In file included from /tmp/binarydeb/ros-noetic-multisense-ros-4.0.4/src/camera.cpp:34:
16:47:56 /tmp/binarydeb/ros-noetic-multisense-ros-4.0.4/include/multisense_ros/camera.h:243:5: error: ‘CvMat’ does not name a type
16:47:56   243 |     CvMat *calibration_map_left_1_;
```

Since the Debian Buster builds are passing, is it that this package has not been updated to support OpenCV 4.2?

**Comment by QuentinTorg** [comment]
Yes, this package was not yet updated for OpenCV 4.2. Thanks again for catching this. 

This will be resolved once ros/rosdistro#26042 is merged
