### ISSUE TITLE
Multiple Root Links If Using the Importable URDF Xacro File

### ISSUE THREAD

**Issue by swiz23** [carnegierobotics/multisense_ros#59]
https://github.com/carnegierobotics/multisense_ros/blob/9464c37d91a62f9a72f20ca39a16575fc94c886d/multisense_description/urdf/multisenseKS21/importable.urdf.xacro#L8-L12

The multisenseKS21.urdf.xacro has a tree where both the `head` and the `imu` links are children of `left_camera_optical_frame`. However, the importable.urdf.xacro file tries to create a parent/child relationship between `parent` and `head`. This will cause there to be multiple root links in the urdf. To fix this, the multisenseKS21.urdf.xacro file should have `head` as the root link with the `left_camea_optical_frame` and `imu` as children.

**Comment by swiz23** [comment]
just noticed that this seems to be a bug not just for the ks21 camera, but for all of the cameras here.

**Comment by mattalvarado** [comment]
Hopefully this is resolved in #61. I am curious what your use case is here, since the ROS driver only utilizes the standalone xacro files in the multisense_bringup launch file.

**Comment by swiz23** [comment]
No use case. I was just browsing through the urdfs and realized that if one were to use the importable urdf, there would be this issue.

**Comment by mattalvarado** [comment]
Understood. To avoid confusion I will update this PR to remove those files. I think they were artifacts from a old Gazebo setup we previously supported, but at the moment I don't think anyone uses them.
