### ISSUE TITLE
Add Mounting Link Frame to URDFs

### ISSUE THREAD

**Issue by swiz23** [carnegierobotics/multisense_ros#60]
Would it be possible to add a 'mount_frame' link to the urdfs so that we can easily attach these cameras to our robots?

**Comment by mattalvarado** [comment]
We could include an nominal CAD mounting position, but ideally you would calibrate the pose of the MultiSense relative to robot using one of the observable camera coordinate frames.

**Comment by swiz23** [comment]
That's true. But it does help with giving you a ballpark idea of what the calibrated transform should look like. Also, it comes in handy if you aren't ready to do a calibration for your robot yet. That said, at least for the KS21, its kind of arbitrary how you would define that mounting link since there are screw holes on either side of the camera housing. I think I'll plan on using the spec sheet to help create my desired mount frame. Closing as I have a path forward. 

Thanks
