### ISSUE TITLE
Error in building the driver via source compilation for Ros Noetic

### ISSUE THREAD

**Issue by poornimajd** [carnegierobotics/multisense_ros#93]
Hi, 

I am getting the following error, when I try to build the driver for Ros noetic. The OpenCv Version is 4.6. I am building it on Jetson Orin, Ubuntu 20.04

![Screenshot from 2024-06-27 19-58-49](https://github.com/carnegierobotics/multisense_ros/assets/31023599/c37ae432-8fbb-4367-817c-874499a40a85)

Any suggestion would be appreciated!

Thank you

**Comment by mattalvarado** [comment]
Hi @poornimajd,

This is a common issue with Nvidia platforms. Please see this answer in our new beta documentation: https://docs.carnegierobotics.com/docs/faq/faq.html#why-does-the-multisense-ros-driver-fail-to-build-on-nvidia-jetson-platforms

**Comment by poornimajd** [comment]
After removing multiple versions of opencv, the issue is resolved.
