### ISSUE TITLE
Unable to connect multisense

### ISSUE THREAD

**Issue by poornimajd** [carnegierobotics/multisense_ros#94]
Hi, 
I set the ipv4 address of the multisense s30 manually, 
IP address: 10.66.171.21
Netmask: 255.255.240.0
Gateway:10.66.171.1

I am unable to connect to the multisense using this command:

`roslaunch multisense_bringup multisense.launch
`
I even tried specifiying the ip_address and mtu parameters.

I am working on Jetson orin, and when I try to set the mtu, I get the following:
`sudo ifconfig eth0 mtu 7200 `
Output is :  `SIOCSIFMTU: Device or resource busy `
I tried even tried to 
```
sudo ifconfig eth0 down
sudo ifconfig eth0 up
```

The output of `ifconfig eth0:
`
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1466
        inet 10.66.171.21  netmask 255.255.240.0  broadcast 10.66.175.255
        inet6 fe80::c545:2575:b730:52df  prefixlen 64  scopeid 0x20<link>
        ether 48:b0:2d:90:2f:e2  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 4710 (4.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
Any suggestion would be greatly appreciated, Thanks!

**Comment by mattalvarado** [comment]
@poornimajd It looks like you set your host network interface to the same IP address as the camera. If you configure your Orin to have a Static IP address of 10.66.171.22 you will not conflict with the camera at 10.66.171.21.

Please reference this guide for setting the IP address and MTU of your host system
https://docs.carnegierobotics.com/docs/network/host_configuration/linux.html#static-ip-address

**Comment by poornimajd** [comment]
Works as expected now, Thank you
